#config_version=6
# this is a test! doesitupdatethecodeautomatically to onedrive?
mode:
  start_events: mode_base_started

slide_player:
  counter_flash_count_hit{count==1}:
    flash_x1:
      expire: 7.1s
      priority: 900
  counter_flash_count_hit{count==2}:
    flash_x1:
      expire: 7.1s
      priority: 900
  counter_flash_count_hit{count==3}:
    flash_x1:
      expire: 7.1s
      priority: 900

  counter_batman_count_hit{count==1}:
    batman_x1:
      # expire: 7.1s
      priority: 900
  counter_batman_count_hit{count==2}:
    batman_x2:
      # expire: 7.1s
      priority: 900
  counter_batman_count_hit{count==3}:
    batman_x3:
      # expire: 7.1s
      priority: 900
  counter_batman_count_hit{count==4}:
    batman_x4:
      # expire: 7.1s
      priority: 900

  shot_line_1_hit:
    cyborg_x1:
      # expire: 7.1s
      priority: 900
  shot_line_2_hit:
    cyborg_x2:
      # expire: 7.1s
      priority: 900
  shot_line_3_hit:
    cyborg_x3:
      # expire: 7.1s
      priority: 900

  counter_superman_count_hit{count==1}:
    superman_x1:
      # expire: 7.1s
      priority: 900
  counter_superman_count_hit{count==2}:
    superman_x2:
      # expire: 7.1s
      priority: 900
  counter_superman_count_hit{count==3}:
    superman_x3:
      # expire: 7.1s
      priority: 900
  counter_superman_count_hit{count==4}:
    superman_x4:
      # expire: 7.1s
      priority: 900

  counter_aquaman_count_hit{count==1}:
    aquaman_x1:
      # expire: 7.1s
      priority: 900
  counter_aquaman_count_hit{count==2}:
    aquaman_x2:
      # expire: 7.1s
      priority: 900
  counter_aquaman_count_hit{count==3}:
    aquaman_x3:
      # expire: 7.1s
      priority: 900

  shot_left_drop_left_hit:
      wonder_woman_x1:
        # expire: 7.1s
        priority: 900
  shot_left_drop_middle_hit:
      wonder_woman_x2:
        # expire: 7.1s
        priority: 900
  shot_left_drop_right_hit:
      wonder_woman_x3:
        # expire: 7.1s
        priority: 900
  shot_right_drop_left_hit:
      wonder_woman_x4:
        # expire: 7.1s
        priority: 900
  shot_right_drop_middle_hit:
      wonder_woman_x5:
        # expire: 7.1s
        priority: 900
  shot_right_drop_right_hit:
      wonder_woman_x6:
        # expire: 7.1s
        priority: 900

shots:
  justice_league_multiball:
    switch: s_mystery_scoop
  character_select:
    switch: s_mystery_scoop

achievements:
  justice_league_assembled:
    start_events: justice_league_count_complete
    # complete_events: justice_league_assembled
    events_when_completed: justice_league_multiball_lit 
    show_when_started: justice_league_lit
    show_when_completed: justice_league_complete
    reset_events: justice_league_count_reset

    # show_when_enabled:

  batman_assembled:
    start_events: shot_left_ramp_hit
    complete_events: batman_count_complete
    events_when_completed: character_select_lit
    show_when_completed: batman_complete 
    reset_events: justice_league_count_reset

    # show_when_enabled:

  wonder_woman_assembled:
    start_events: shot_left_drop_left_hit, shot_left_drop_middle_hit, shot_left_drop_right_hit, shot_right_drop_right_hit, shot_right_drop_middle_hit, shot_right_drop_left_hit
    complete_events: wonder_woman_count_complete
    events_when_completed: character_select_lit
    show_when_completed: wonder_woman_complete
    reset_events: justice_league_count_reset
 
    # show_when_enabled:

  flash_assembled:
    start_events: shot_orbit_left_hit
    complete_events: flash_count_complete
    events_when_completed: character_select_lit
    show_when_completed: flash_complete 
    reset_events: justice_league_count_reset 
    # show_when_enabled:

  cyborg_assembled:
    start_events: shot_line_1_hit
    complete_events: cyborg_count_complete
    events_when_completed: character_select_lit
    show_when_completed: cyborg_complete   
    reset_events: justice_league_count_reset 
    # show_when_enabled:

  superman_assembled:
    start_events: shot_right_ramp_hit
    complete_events: superman_count_complete
    events_when_completed: character_select_lit
    show_when_completed: superman_complete
    reset_events: justice_league_count_reset 
    # show_when_enabled:

  aquaman_assembled:
    start_events: shot_orbit_right_hit
    complete_events: aquaman_count_complete
    events_when_completed: character_select_lit
    show_when_completed: aquaman_complete
    reset_events: justice_league_count_reset 
    # show_when_enabled:

accruals:
  justice_league_count_complete:
    events: wonder_woman_count_complete, cyborg_count_complete, flash_count_complete, batman_count_complete, superman_count_complete, aquaman_count_complete
    events_when_complete: justice_league_count_complete
    persist_state: true
    reset_events: justice_league_count_reset
    disable_on_complete: false

  justice_league_assembled:
    events: justice_league_count_complete, justice_league_multiball_hit
    events_when_complete: start_justice_league_multiball, justice_league_completion_points
    persist_state: true
    reset_events: justice_league_count_reset
    disable_on_complete: false

  cyborg_count:
    events: shot_line_1_hit, shot_line_2_hit, shot_line_3_hit, shot_line_kickback_hit
    events_when_complete: cyborg_count_complete, cyborg_completion_points
    reset_on_complete: false
    persist_state: true
    reset_events: justice_league_count_reset
    disable_on_complete: false

  wonder_woman_count:
    events: shot_left_drop_left_hit, shot_left_drop_middle_hit, shot_left_drop_right_hit, shot_right_drop_right_hit, shot_right_drop_middle_hit, shot_right_drop_left_hit
    events_when_complete: wonder_woman_count_complete, wonder_woman_completion_points
    reset_on_complete: false
    persist_state: true
    reset_events: justice_league_count_reset
    disable_on_complete: false

  character_select_start:
    events: character_select_lit, shot_mystery_scoop_hit
    events_when_complete: start_character_select_mode
    disable_on_complete: false

  # justice_league_multiball_start:
  #   events: justice_league_multiball_lit, shot_mystery_scoop_hit, character_select_lit
  #   events_when_complete: start_justice_league_multiball
  #   disable_on_complete: false

counters:
  flash_count:
    starting_count: 0
    count_complete_value: 3
    count_events: shot_orbit_left_hit
    events_when_complete: flash_count_complete, flash_completion_points
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false
    reset_events: justice_league_count_reset

  superman_count:
    starting_count: 0
    count_complete_value: 4
    count_events: shot_right_ramp_hit
    events_when_complete: superman_count_complete, superman_completion_points
    persist_state: true
    reset_on_complete: false
    disable_on_complete: false
    reset_events: justice_league_count_reset

  aquaman_count:
    starting_count: 0
    count_complete_value: 3
    count_events: shot_orbit_right_hit
    events_when_complete: aquaman_count_complete, aquaman_completion_points
    persist_state: true
    reset_on_complete: false
    reset_events: justice_league_count_reset
    disable_on_complete: false
    disable_events: 

  batman_count:
    starting_count: 0
    count_complete_value: 4
    count_events: shot_left_ramp_hit
    reset_on_complete: false
    events_when_complete: batman_count_complete, batman_completion_points
    persist_state: true
    disable_on_complete: false
    reset_events: justice_league_count_reset

variable_player:
  flash_count_complete:
    flash_mode_status:
      action: set
      string: complete
    flash_cycle_multi: 1
  counter_flash_count_hit:
    flash_last_award:
      int: 10000 * device.counters.flash_count.value * current_player.flash_cycle_mult
    score: 10000 * device.counters.flash_count.value * current_player.flash_cycle_mult

  superman_count_complete:
    superman_mode_status:
      action: set
      string: complete
    superman_cycle_multi: 1
  counter_superman_count_hit:
    superman_last_award:
      int: 10000 * device.counters.superman_count.value * current_player.superman_cycle_mult
    score: 10000 * device.counters.superman_count.value * current_player.superman_cycle_mult

  aquaman_count_complete:
    aquaman_mode_status:
      action: set
      string: complete
    aquaman_cycle_multi: 1
  counter_aquaman_count_hit:
    aquaman_last_award:
      int: 10000 * device.counters.aquaman_count.value * current_player.aquaman_cycle_mult
    score: 10000 * device.counters.aquaman_count.value * current_player.aquaman_cycle_mult

  batman_count_complete:
    batman_mode_status:
      action: set
      string: complete
    batman_cycle_multi: 1
  counter_batman_count_hit:
    batman_last_award:
      int: 10000 * device.counters.batman_count.value * current_player.batman_cycle_mult
    score: 10000 * device.counters.batman_count.value * current_player.batman_cycle_mult

  wonder_woman_count_complete:
    wonder_woman_mode_status:
      action: set
      string: complete
    wonder_woman_cycle_multi: 1
  counter_wonder_woman_count_hit:
    wonder_woman_last_award:
      int: 10000 * device.counters.wonder_woman_count.value * current_player.wonder_woman_cycle_mult
    score: 10000 * device.counters.wonder_woman_count.value * current_player.wonder_woman_cycle_mult
    
  cyborg_count_complete:
    cyborg_mode_status:
      action: set
      string: complete
    cyborg_cycle_multi: 1
  counter_cyborg_count_hit:
    cyborg_last_award:
      int: 10000 * device.counters.cyborg_count.value * current_player.cyborg_cycle_mult
    score: 10000 * device.counters.cyborg_count.value * current_player.cyborg_cycle_mult

  wonder_woman_completion_points:
    score: 250000
  flash_completion_points:
    score: 250000
  batman_completion_points:
    score: 250000
  cyborg_completion_points:
    score: 250000
  superman_completion_points:
    score: 250000
  aquaman_completion_points:
    score: 250000
  justice_league_completion_points:
    score: 500000

light_player:
  shot_right_drop_left_hit:
    l_right_drop_left: yellow
  shot_right_drop_middle_hit:
    l_right_drop_middle: yellow
  shot_right_drop_right_hit:
    l_right_drop_right: yellow
  shot_left_drop_right_hit:
    l_left_drop_right: yellow
  shot_left_drop_middle_hit:
    l_left_drop_middle: yellow
  shot_left_drop_left_hit:
    l_left_drop_left: yellow

  counter_superman_count_hit{count == 1}:
    l_right_ramp_3: blue
  counter_superman_count_hit{count == 2}:
    l_right_ramp_2: blue
  counter_superman_count_hit{count == 3}:
    l_right_ramp_1: blue
  counter_superman_count_hit{count == 4}:
    l_right_ramp_arrow: blue

  counter_batman_count_hit{count == 1}:
    l_left_ramp_3: yellow
  counter_batman_count_hit{count == 2}:
    l_left_ramp_2: yellow
  counter_batman_count_hit{count == 3}:
    l_left_ramp_1: yellow
  counter_batman_count_hit{count == 4}:
    l_left_ramp_arrow: yellow

  counter_flash_count_hit{count == 1}:
    l_orbit_left_3: red
  counter_flash_count_hit{count == 2}:
    l_orbit_left_2: red
  counter_flash_count_hit{count == 3}:
    l_orbit_left_1: red

  counter_aquaman_count_hit{count == 1}:
    l_orbit_right_3: green
  counter_aquaman_count_hit{count == 2}:
    l_orbit_right_2: green
  counter_aquaman_count_hit{count == 3}:
    l_orbit_right_1: green

  shot_line_kickback_hit:
    l_line: red

  mode_justice_league_multiball_will_stop:
    l_left_ramp_arrow: off
    l_left_ramp_1: off
    l_left_ramp_2: off
    l_left_ramp_3: off
    l_right_ramp_arrow: off
    l_right_ramp_1: off
    l_right_ramp_2: off
    l_right_ramp_3: off
    l_line: off
    l_mystery: off
    l_orbit_left_arrow: off
    l_orbit_left_1: off
    l_orbit_left_2: off
    l_orbit_left_3: off
    l_right_drop_right: off
    l_right_drop_middle: off
    l_right_drop_left: off
    l_left_drop_left: off
    l_left_drop_middle: off
    l_left_drop_right: off
    l_orbit_right_arrow: off
    l_orbit_right_1: off
    l_orbit_right_2: off
    l_orbit_right_3: off
    l_batman: off
    l_superman: off
    l_flash: off
    l_cyborg: off
    l_aquaman: off
    l_wonder_woman: off
    l_steppenwolf: off
    l_main_drop_left: off
    l_main_drop_middle: off
    l_main_drop_right: off
    l_jet_lane_left: off
    l_jet_lane_middle: off
    l_jet_lane_right: off
    l_outlane_left: off
    l_outlane_right: off
    l_inlane_left: off
    l_inlane_right: off
    l_justice_league: off



blinkenlight_player:
  character_select_lit:
    blinkenlight_character_select:
      color: blue

  justice_league_multiball_lit:
    blinkenlight_character_select:
      color: blue
  
  mode_character_select_will_start:
    blinkenlight_character_select:
      action: remove

  mode_justice_league_multiball_will_start:
    blinkenlight_character_select:
      action: remove

  counter_superman_count_hit{count == 1}:
    blinkenlight_right_ramp_x2:
      color: blue
  counter_superman_count_hit{count == 2}:
    blinkenlight_right_ramp_x3:
      color: blue
    blinkenlight_right_ramp_x2: remove
  counter_superman_count_hit{count == 3}:
    blinkenlight_right_ramp_arrow:
      color: blue
    blinkenlight_right_ramp_x3: remove
  counter_superman_count_hit{count == 4}:
    blinkenlight_right_ramp_arrow: remove

  counter_batman_count_hit{count == 1}:
    blinkenlight_left_ramp_x2:
      color: yellow
  counter_batman_count_hit{count == 2}:
    blinkenlight_left_ramp_x3:
      color: yellow
    blinkenlight_left_ramp_x2: remove
  counter_batman_count_hit{count == 3}:
    blinkenlight_left_ramp_arrow:
      color: yellow
    blinkenlight_left_ramp_x3: remove
  counter_batman_count_hit{count == 4}:
    blinkenlight_left_ramp_arrow: remove

  counter_flash_count_hit{count == 1}:
    blinkenlight_left_orbit_x2:
      color: red
  counter_flash_count_hit{count == 2}:
    blinkenlight_left_orbit_x3:
      color: red
    blinkenlight_left_orbit_x2: remove
  counter_flash_count_hit{count == 3}:
    blinkenlight_left_orbit_x3: remove
  
  counter_aquaman_count_hit{count == 1}:
    blinkenlight_right_orbit_x2:
      color: green
  counter_aquaman_count_hit{count == 2}:
    blinkenlight_right_orbit_x3:
      color: green
    blinkenlight_right_orbit_x2: remove
  counter_aquaman_count_hit{count == 3}:
    blinkenlight_right_orbit_x3: remove

  shot_line_3_hit:
    blinkenlight_cyborg:
      color: red
  shot_line_kickback_hit:
    blinkenlight_cyborg: remove