#config_version=6

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger
    # eject_coil: c_plunger_eject
    eject_targets: playfield
    tags: plunger
    mechanical_eject: true
    eject_timeouts: 5s
     # player_controller_eject_event: s_lockbar
  bd_mystery_scoop:
    ball_switches: s_mystery_scoop
    eject_coil: c_mystery_scoop
    eject_timeouts: 1s

  # bd_steppenwolf:
  #   ball_switches: s_steppenwolf
  #   eject_coil: c_steppenwolf_eject
  #   eject_targets: bd_mystery_scoop
  #   tags: steppenwolf, scoop
  #   eject_timeouts: 3s
  #   confirm_eject_type: target

   

  # bd_main_kickback:
  #   ball_switches: s_main_kickback
  #   eject_coil: c_main_kickback
  #   eject_timeouts: 1s
  # bd_line_kickback:
  #   ball_switches: s_line_kickback
  #   eject_coil: c_line_kickback
  #   eject_timeouts: 1s