#config_version=6

keyboard:
  debug: yes
  "1":
    switch: s_trough1
    toggle: true
  "2":
    switch: s_trough2
    toggle: true
  "3":
    switch: s_trough3
    toggle: true
  "4":
    switch: s_trough4
    toggle: true
  "5":
    switch: s_trough5
    toggle: true
  "6":
    switch: s_trough6
    toggle: true
  "o":
    switch: s_orbit_left
  "s":
    switch: s_start
  "p":
    switch: s_plunger
  "a":
    switch: s_plunger_lane
  "7":
    switch: s_main_drop_left
    toggle: true
  "8":
    switch: s_main_drop_middle
    toggle: true
  "9":
    switch: s_main_drop_right
    toggle: true

  # ---- Steppenwolf shot switch (momentary is fine, but toggle also ok) ----
  "0":
    switch: s_steppenwolf
    # toggle: true

drop_targets:
  drop_main_left:
    switch: s_main_drop_left
  drop_main_middle:
    switch: s_main_drop_middle
  drop_main_right:
    switch: s_main_drop_right

drop_target_banks:
  center_bank:
    drop_targets: drop_main_left, drop_main_middle, drop_main_right
    reset_events: ball_starting, drop_target_bank_center_bank_reset
 
switches:
  # cabinet switches
  s_left_flipper:
    number: 0
    tags: left_flipper
  s_right_flipper:
    number: 1
    tags: right_flipper
  s_trough1:
    number: 2
  s_trough2:
    number: 3
  s_trough3:
    number: 4
  s_trough4:
    number: 5
  s_trough5:
    number: 6
  s_trough6:
    number: 7
  s_trough_jam:
    number: 8
  s_plunger:
    number: 9
  s_plunger_lane:
    number: 10
    tags: playfield_active
  s_launch_button:
    number: 11
  s_start:
    number: 12
    tags: start
  s_lockbar:
    number: 47

  # Playfield Switches
  s_right_inlane:
    number: 13
    tags: playfield_active
  s_left_inlane:
    number: 14
    tags: playfield_active
  s_orbit_top:
    number: 15
    tags: playfield_active
  s_orbit_right:
    number: 18
    tags: playfield_active
  s_orbit_left:
    number: 19
    tags: playfield_active
  s_slingshot_left:
    number: 20
    tags: playfield_active
  s_slingshot_right:
    number: 21
    tags: playfield_active
  s_pop_bumper_left:
    number: 22
    # tags: playfield_active
  s_pop_bumper_right:
    number: 23
    # tags: playfield_active
  s_pop_bumper_bottom:
    number: 24
    # tags: playfield_active
  s_main_drop_left:
    number: 25
    type: NC
    # tags: playfield_active
  s_main_drop_middle:
    number: 26
    type: NC
    # tags: playfield_active
  s_main_drop_right:
    number: 27
    type: NC
    # tags: playfield_active
  s_steppenwolf:
    number: 28
    # tags: playfield_active
  # s_main_kickback:
  #   number: 29
  s_left_drop_left:
    number: 30
    tags: playfield_active
  s_left_drop_middle:
    number: 31
    tags: playfield_active
  s_left_drop_right:
    number: 32
    tags: playfield_active
  s_right_drop_right:
    number: 33
    tags: playfield_active
  s_right_drop_middle:
    number: 34
    tags: playfield_active
  s_right_drop_left:
    number: 35
    tags: playfield_active
  s_mystery_drop:
    number: 36
    tags: playfield_active
  s_mystery_scoop:
    number: 37
  s_line_drop_1:
    number: 38
    tags: playfield_active
  s_line_drop_2:
    number: 39
    tags: playfield_active
  s_line_drop_3:
    number: 40
    tags: playfield_active
  s_line_kickback:
    number: 41
  s_spinner:
    number: 42
    tags: playfield_active
  s_left_ramp:
    number: 43
    tags: playfield_active
  s_right_ramp:
    number: 44
    tags: playfield_active
  s_left_outlane:
    number: 45
    tags: playfield_active
  s_right_outlane:
    number: 46
    tags: playfield_active
  s_jet_lane_left:
    number: 48
  s_jet_lane_middle:
    number: 49
  s_jet_lane_right:
    number: 50