#config_version=6

mode:
  start_events: start_batman_mode
  stop_events: stop_mode_batman, start_character_select_mode
  priority: 600

variable_player:
  shot_left_ramp_hit:
    score: 25000
  mode_batman_started:
    score: 1000000

# Show character select first, then (when it is removed) show the background loop slide.
slide_player:
  mode_batman_started:
    batman_character_select:
      priority: 900
      expire: 5s

  # This event is automatically posted when the above slide expires/removes
  slide_batman_character_select_removed:
    batman_mode_background:
      priority: 100

# Clean up the background slide when the mode ends (prevents “stuck” video layers)
event_player:
  mode_batman_stopping:
    remove_slide:
      slide: batman_mode_background

sound_player:
  slide_batman_character_select_removed:
    batman_theme:
      action: play
      loops: -1
      bus: music
      volume: 0.05

  mode_batman_stopping:
    batman_theme:
      action: stop
      bus: music
