#config_version=6

mode:
  # TWO DIFFERENT START EVENTS:
  # - start_character_select_mode               = start-of-game
  # - start_character_select_mode_from_scoop    = later re-select from scoop
  start_events: start_character_select_mode, start_character_select_mode_from_scoop
  stop_events: character_select_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 500

mode_settings:
  selectable_items:
    # keep SIMPLE for now so it canâ€™t go items_empty
    - wonder_woman
    - flash
    - batman
    - cyborg
    - superman
    - aquaman

  select_item_events: s_lockbar_active
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
  mode_character_select_started: character_select

# Track highlight + selection
variable_player:

  mode_character_select_will_start{mode.starting_event=="start_character_select_mode"}:
    select_filter_completed_only:
      action: set
      int: 0

  mode_character_select_will_start{mode.starting_event=="start_character_select_mode_from_scoop"}:
    select_filter_completed_only:
      action: set
      int: 1


  # Highlighted
  character_select_wonder_woman_highlighted:
    highlighted_character:
      string: "Wonder Woman"
      action: set
  character_select_flash_highlighted:
    highlighted_character:
      string: "Flash"
      action: set
  character_select_batman_highlighted:
    highlighted_character:
      string: "Batman"
      action: set
  character_select_cyborg_highlighted:
    highlighted_character:
      string: "Cyborg"
      action: set
  character_select_superman_highlighted:
    highlighted_character:
      string: "Superman"
      action: set
  character_select_aquaman_highlighted:
    highlighted_character:
      string: "Aquaman"
      action: set

  # Selected
  character_select_wonder_woman_selected:
    selected_character:
      string: "Wonder Woman"
      action: set
  character_select_flash_selected:
    selected_character:
      string: "Flash"
      action: set
  character_select_batman_selected:
    selected_character:
      string: "Batman"
      action: set
  character_select_cyborg_selected:
    selected_character:
      string: "Cyborg"
      action: set
  character_select_superman_selected:
    selected_character:
      string: "Superman"
      action: set
  character_select_aquaman_selected:
    selected_character:
      string: "Aquaman"
      action: set

sound_player:
  item_highlighted{item=="wonder_woman"}:
    wonder_woman_theme:
      action: play
      loops: -1
      bus: music
      fade_in: 1s
    flash_theme:
      action: stop
      bus: music
      fade_out: 500ms
    aquaman_theme:
      action: stop
      bus: music
      fade_out: 500ms

  item_highlighted{item=="flash"}:
    flash_theme:
      action: play
      loops: -1
      start_at: 4s
      bus: music
      fade_in: 1s
    wonder_woman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    batman_theme:
      action: stop
      bus: music
      fade_out: 500ms

  item_highlighted{item=="batman"}:
    batman_theme:
      action: play
      loops: -1
      bus: music
      fade_in: 1s
    flash_theme:
      action: stop
      bus: music
      fade_out: 500ms
    cyborg_theme:
      action: stop
      bus: music
      fade_out: 500ms

  item_highlighted{item=="cyborg"}:
    cyborg_theme:
      action: play
      loops: -1
      start_at: 360s
      bus: music
      fade_in: 1s
    batman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    superman_theme:
      action: stop
      bus: music
      fade_out: 500ms

  item_highlighted{item=="superman"}:
    superman_theme:
      action: play
      loops: -1
      start_at: 2s
      bus: music
      fade_in: 1s
    cyborg_theme:
      action: stop
      bus: music
      fade_out: 500ms
    aquaman_theme:
      action: stop
      bus: music
      fade_out: 500ms

  item_highlighted{item=="aquaman"}:
    aquaman_theme:
      action: play
      loops: -1
      start_at: 10s
      bus: music
      fade_in: 1s
    wonder_woman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    superman_theme:
      action: stop
      bus: music
      fade_out: 500ms

  character_select_item_selected:
    wonder_woman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    flash_theme:
      action: stop
      bus: music
      fade_out: 500ms
    batman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    cyborg_theme:
      action: stop
      bus: music
      fade_out: 500ms
    superman_theme:
      action: stop
      bus: music
      fade_out: 500ms
    aquaman_theme:
      action: stop
      bus: music
      fade_out: 500ms
