#config_version=6

mode:
  start_events: start_flash_mode,
  stop_events: stop_mode_flash, start_character_select_flash
  priority: 600

variable_player: 
  # shot_left_ramp_hit:
  #   score: 25000
  # mode_batman_started:
  #   score: 1000000
 
slide_player:
  mode_flash_started: 
    flash_character_select:
      expire: 5s

sound_player:
  slide_flash_character_select_removed: 
    flash_theme:
      action: play
      loops: -1
      bus: music
      volume: 0.5
      start_at: 9s